### ISSUE TITLE
Animation during rotation

### ISSUE THREAD

**Issue by frankl988** [erichoracek/MSCollectionViewCalendarLayout#17]
First: great component! congrats!
I am trying to have realistic animations during rotation. The current situation is, that the different content views (supplementary and items) switch with an fade between the wider lansdcape state and the smaller portrait state which looks pretty clumpsy. I want them to change width during rotation. Any ideas? 

Currently I do an ```invalidateLayoutCache``` during ```willRotateToInterfaceOrientation:duration:```.

**Comment by erichoracek** [comment]
I know this is a late response, but the example project should be updated to properly animate while rotating by using the new `-[UIViewController willTransitionToTraitCollection:withTransitionCoordinator:]` method.
