### ISSUE TITLE
directionLockEnabled = YES; but not working problem. help me guys :)

### ISSUE THREAD

**Issue by Sodtseren** [erichoracek/MSCollectionViewCalendarLayout#18]
i want direction lock, only portrait or only landscape scrolling?

**Comment by MoKeS-** [comment]
What he meant I think was to prevent users to scroll in both direction (horizontal and vertical) at the same time. I had the same concern. Direction lock was working partially but I found a way to have a complete workaround : 

http://bogdanconstantinescu.com/blog/proper-direction-lock-for-uiscrollview.html
