### ISSUE TITLE
Suggestions for additional features

### ISSUE THREAD

**Issue by nishiarya** [erichoracek/MSCollectionViewCalendarLayout#27]
With respect to the default iOS iPad week calendar, i would like to suggest to add below option in this calendar:
1. Display all dates even there are no events to display.
2. Display all day events like Birthday and AM/PM events.
3. Add new events by selecting the grid cell like on default iOS.
4. Edit available events by selection.
5. Move events one column to other and change timings of events.
6. Display multiple users events.

Please let me know how much flexibility is available in this calendar to add above features?

Great Work Thanks a Lot!

**Comment by BadChoice** [comment]
Check this out, I've implemented some of the features you're looking for

https://github.com/BadChoice/RVCalendarWeekView

√ Display all dates even there are no events to display.
√ Add new events by selecting the grid cell like on default iOS.
√ Edit available events by selection.
√ Move events one column to other and change timings of events.
Display multiple users events. => you can do it with different events classes

**Comment by nishiarya** [comment]
Wow thanks allot, it's really helps everyone.
