### ISSUE TITLE
Show all dates even if there is no event attached to date

### ISSUE THREAD

**Issue by rahulvyas** [erichoracek/MSCollectionViewCalendarLayout#30]
Hi,

Is it possible to show all dates of a month even if there is no event attached to a specific date ?

**Comment by sree127** [comment]
Hey, is there a way to show the 24 hour time even if there are no events attached to a date?

**Comment by erichoracek** [comment]
@sree127 If you combine the above approach with the subclassing method in #53 you should be able to achieve the desired effect.
