### ISSUE TITLE
Storyboard

### ISSUE THREAD

**Issue by ferkel13** [erichoracek/MSCollectionViewCalendarLayout#32]
Hi!

The Example works perfectly! But could you please provide an example how to use this great control with storyboard? Thanks!

**Comment by ararog** [comment]
@ferkel13 how you did that? Place a UIView or UICollectionView and changed the class from inspector?
Can you provide more details?

**Comment by ferkel13** [comment]
Hi there!

Yep, just place UICollectionView and change some props
