### ISSUE TITLE
StartTime of the Event

### ISSUE THREAD

**Issue by ferkel13** [erichoracek/MSCollectionViewCalendarLayout#34]
Hi!
I've got a weird issue with a StartTime of Events. In my json-output the StartTime is e.g. 13:00, but the Layout shows it as 16:00 ( + 3 hours). Can anyone help me?

**Comment by erichoracek** [comment]
@ferkel13 I know this is a late response, but it sounds like this is less related to the implementation of `MSCollectionViewCalendarLayout` and more related to your deserialization logic. Please reopen if this is not the case.
