### ISSUE TITLE
Force UICollectionView to reload it's data source

### ISSUE THREAD

**Issue by jchnxu** [erichoracek/MSCollectionViewCalendarLayout#47]
### Background

I  try to implement an infinite scroll feature. (First fill the collectionView with cells. When scrolled to the bounds, reload the data and scroll the collectionView to the center. Details described in Advanced Scroll View Techniques @ https://developer.apple.com/videos/wwdc/2011/ )
### Problem

 I do something like this when scrolled to the edges:

```
[collectionView.dataSource doSomeUpdate];
[self.collectionView reloadData];
self.collectionView.contentOffset = CGPointMake(currentOffset.x + someOffset.x, currentOffset.y + someOffset.y);
```

These lines are placed in viewDidLayoutSubviews, which is on main thread.
After the executions above. I got errors:
### Errors

```
*** Assertion failure in -[UICollectionViewData validateLayoutInRect:], /SourceCache/UIKit_Sim/UIKit-3318/UICollectionViewData.m:417
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'UICollectionView received layout attributes for a cell with an index path that does not exist: <NSIndexPath: 0xc0000000001c03d6> {length = 2, path = 15 - 56}'
```
### My Analysis

In my implementation, I have 48 or more than 48 cells for each section. 48 means the number of half-hour-cells I used to fill a section. The rest of them are event cells.
So the problem is I have section 15 initially configured to 58 items. After `[self.collectionView reloadData]`, section 15 contains 48 items. I got attributes for indexPaths like 15-48, 15-49,.....15-57 in self.collectionViewCalendarLayout.
### My debugging attempts

I tracked the bug down to `[MSCollectionViewCalendarLayout layoutAttributesForElementsInRect:]`, In this method, `[self.collectionView numberOfItemsInSection:]` returns 58 for section 15, `[self.collectionView.dataSource collectionView:numberOfItemsInSection:]` returns 48 for section 15.
### Conclusions and questions

Data source of the collectionView is updated while the layout cache in collectionView stays the same. It's not the layout cache that `MSCollectionViewCalendarLayout` implemented like `allAttributes`, but the layout cache in `UICollectionView`. Using [MSCollectionViewCalendarLayout invalidateLayoutCache] won't do any good because it's slow and it breaks the scrolling to date function of the custom layout. **So how can I refresh the UICollectionView to force reload it's data source?**

**Comment by iworkinprogress** [comment]
You find a way to reload the data without calling invalidateLayoutCache?

I'm running into a similar issue where I have about ~18,000 sections and calling invalidateLayoutCache is super slow because it loops through each of those sections to perform calculations when you call invalidateLayoutCache. That might work for me if it only occurred once but unfortunately I need to reload the cells in my UICollectionView frequently.

**Comment by jchnxu** [comment]
@iworkinprogress actually I hacked to solve my problem. There're always problems when I try to reload one section, the cells are not displaying properly and collectionView.dataSouce does not update. I tried to make it perfect at the time but I found it was time consuming! I suggest that you find a work around, not attack the problem directly because it's a little complicated.

**Comment by BadChoice** [comment]
check it out

https://github.com/BadChoice/RVCalendarWeekView

I've forked the repo to add some new features and infinite scrolling is one of them, however, it needs to invalidate the cache everytime something new is added.. but I'm open to suggestions
