### ISSUE TITLE
Can I have the iPad view in iPhone?

### ISSUE THREAD

**Issue by tszkanlo** [erichoracek/MSCollectionViewCalendarLayout#52]
Hello! I am working on an calendar. I would like to have the native ios calendar landscape view, and that is similar to the iPad view of this sample. Can I have that on iPhone? Thank you very much!

**Comment by filiroman** [comment]
yes you just have to choose layout type explicitly:
_collectionViewLayout.sectionLayoutType = MSSectionLayoutTypeHorizontalTile;
