### ISSUE TITLE
Show 24 hours time even if there is no event

### ISSUE THREAD

**Issue by sree127** [erichoracek/MSCollectionViewCalendarLayout#53]
Is there a way to show the entire time starting from 0:00 to 23:00 even If there are no events?

**Comment by jwyld** [comment]
Subclass MSCollectionViewCalendarLayout and override -earliestHourForSection: and -latestHourForSection: to return 0 and 24, respectively.  Use your subclass instead of MSCollectionViewCalendarLayout on your UICollectionView.

**Comment by natanrolnik** [comment]
Thanks for the suggestion, @jwyld ! 👍
