### ISSUE TITLE
Does anyone get the example working?

### ISSUE THREAD

**Issue by wegascee** [erichoracek/MSCollectionViewCalendarLayout#54]
I get RestKit/RestKit.h file not found. It would be nice to have an example that works. Before I had problems mit pods ...

**Comment by AhnSeongHyun** [comment]
I working through editing Podfile below:



platform :ios, '6.0'

xcodeproj 'Example'

pod 'MSCollectionViewCalendarLayout', :path => '../'

pod 'RestKit', '~> 0.20.0'
pod 'CupertinoYankee', '~> 0.1.0'
pod 'UIColor-HexString', '~> 1.0.0'
pod 'Masonry', :head
