### ISSUE TITLE
Sample Without Coredata

### ISSUE THREAD

**Issue by nelzaatari** [erichoracek/MSCollectionViewCalendarLayout#55]
Hi,

can you please provide a sample without coredata/Restkit, im really interested in using it but we do not use restkit or core data currently in our app,

i really appreciate if you can help us in this

Regards,

**Comment by adku** [comment]
Hi, 

Few hours with this library and it's really easy to change everything also remove RestKit, sample data etc.

This is my little pull request with option to choose coreData or no.

https://github.com/erichoracek/MSCollectionViewCalendarLayout/pull/65
Best regards,
