### ISSUE TITLE
Pods don't work

### ISSUE THREAD

**Issue by Bruno-Piccinin-RealComm** [erichoracek/MSCollectionViewCalendarLayout#57]
Hi,

I'm trying install pods in my application.
My Podfile is the same as the EXAMPLE app

**_platform :ios, '8.0'
xcodeproj 'MY_APPLICATION_NAME'
pod 'MSCollectionViewCalendarLayout', :path => '../'
pod 'RestKit'
pod 'UIColor-HexString'
pod 'Masonry'**_

I launched the command in Terminal
`pod install`

and this is the result

**_Updating local specs repositories
CocoaPods 0.39.0.beta.4 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.
For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.
Analyzing dependencies
Fetching podspec for `MSCollectionViewCalendarLayout` from `../`
Downloading dependencies
Using AFNetworking (1.3.4)
Using ISO8601DateFormatterValueTransformer (0.6.1)
Using MSCollectionViewCalendarLayout (0.1.5)
Using Masonry (0.6.2)
Using RKValueTransformers (1.1.2)
Using RestKit (0.25.0)
Using SOCKit (1.1)
Using TransitionKit (2.1.1)
Using UIColor-HexString (1.1.0)
Generating Pods project
Integrating client project
Sending stats
Sending stats**_

After that I opened MY_APPLICATION.xcworkspace and I tried to add the following classes inside of the groups on EXAMPLE, coping also the groups on my project
- **_Collection View Reusable Views**_
- **_Collection View Cells**_

Then I added the **_MSCalendarViewController.h**_ and **_MSCalendarViewController.h**_ on my project and I tried to CLEAN and BUILD project.

The result is:

**_MSDayColumnHeader.m:35:13: Use of undeclared identifier 'make'**_

**_MSDayColumnHeader.m:34:31: No visible @interface for 'UIView' declares the selector 'makeConstraints:'**_

**_MSCurrentTimeIndicator.m:29:40: No known class method for selector 'colorWithHexString:'**_

**_MSCurrentTimeIndicator.m:33:39: Property 'centerY' not found on object of type 'MSCurrentTimeIndicator *'; did you mean 'center'?**_

**_MSCurrentTimeIndicator.m:34:37: Property 'right' not found on object of type 'MSCurrentTimeIndicator *'**_

It seems like the header pods are no visible.

Can you help me?

**Comment by Bruno-Piccinin-RealComm** [comment]
Can I have an answer please? Everything can be helpful.
Please

**Comment by adku** [comment]
The reason is newer cocoa pods version .

For me helped:
`sudo gem uninstall cocoapods`
And next:
`sudo gem install cocoapods -v 0.38.0
`

`pod install
`

**Comment by andiradulescu** [comment]
@adku why is cocoapods 0.38.0 needed?

**Comment by BadChoice** [comment]
Checkout my fork https://github.com/BadChoice/RVCalendarWeekView
It is updated and with some new features 👯

**Comment by amourreux** [comment]
@BadChoice 
![screen shot 2018-02-25 at 15 00 58](https://user-images.githubusercontent.com/1535873/36641204-c4978ed4-1a3c-11e8-9f4f-bea345d5165b.png)

Problem still there.

**Comment by BadChoice** [comment]
Are you on swift?

**Comment by amourreux** [comment]
@BadChoice nope. Objective-C. any dependency issue maybe?

**Comment by BadChoice** [comment]
Mmm so weird, because it is workin on our side, I tried it in 4 different computes to see if I could reproducte it,
what cocoapods version are you using?

**Comment by amourreux** [comment]
@BadChoice 

```
pod --version
1.4.0
```

**Comment by y0dev** [comment]
has this been fix?

**Comment by BadChoice** [comment]
Not yet, I don't know how to reproduce it yet..

**Comment by sathish211** [comment]
@BadChoice has this issue has been fixed? i am facing same issue in XCode 11.2 Beta. FYI - i am in SWIFT 5.0

![Screen Shot 2019-10-09 at 10 42 02 AM](https://user-images.githubusercontent.com/50426877/66497048-7cfac200-ea81-11e9-92d2-f3d12b2d4e70.png)
