### ISSUE TITLE
Customize earliest schedule hour

### ISSUE THREAD

**Issue by gfpacheco** [erichoracek/MSCollectionViewCalendarLayout#58]
Is there any way of customizing the earliest schedule hour?
I'm trying to find out and even the source code doesn't seem to give this option.

**Comment by muratyasarr** [comment]
Maybe you can try to re-implement  `- (NSInteger)earliestHourForSection:(NSInteger)section` and `- (NSInteger)latestHourForSection:(NSInteger)section` on the source code.

**Comment by muratyasarr** [comment]
What I wrote above definitely solves the issue for fixed earliest hours for all days. However, I cannot overcome setting earliest hours for each day(section) differently. Can anyone please give me a hand on how to achieve it? The only solution that comes to my mind is to add a delegate method like `(NSInteger)earliestHourForSection:(NSInteger)section`

**Comment by BadChoice** [comment]
Checkout my fork https://github.com/BadChoice/RVCalendarWeekView
It is updated and with some new features 👯 
It comes with a use24hours property or not
