### ISSUE TITLE
 Collection view frame resize

### ISSUE THREAD

**Issue by azpery** [erichoracek/MSCollectionViewCalendarLayout#63]
Hi there, 
I love your work, and it's a really fancy component you made here. 
But though I would like to know where you set the frame size? Because I have a TabBar that come over the header day column. 
Thank you very much :) 
Robin

**Comment by BadChoice** [comment]
Checkout my fork https://github.com/BadChoice/RVCalendarWeekView
It is updated and with some new features 👯
