### ISSUE TITLE
Trying to use the library

### ISSUE THREAD

**Issue by rosothefox** [erichoracek/MSCollectionViewCalendarLayout#66]
Hey,

Thanks for your contribution, your library looks awesome, unfortunately it doesn't run for some reason on my Xcode.

```
            dispatch_async(self.successCallbackQueue ?: dispatch_get_main_queue(), ^{

[self didChangeValueForKey:newStateKey];

[self finish];
```

this three lines are probably the problematics ones shown on debug, any idea how to fix it? I want to see the example to understand how it's working, or maybe you have a different example?

Thanks in advance!!

**Comment by BadChoice** [comment]
Checkout my fork https://github.com/BadChoice/RVCalendarWeekView
It is updated and with some new features 👯
