### ISSUE TITLE
Setting Example project on Simulator - Crash

### ISSUE THREAD

**Issue by mikeRozen** [erichoracek/MSCollectionViewCalendarLayout#67]
Setting example app on simulator ios 9.2 produce the following error:

```
restkit.network:RKObjectRequestOperation.m:150 GET 'http://api.seatgeek.com/2/events?lat=39.75&lon=-104.984&per_page=500&range=10mi&taxonomies.name=sports'
2016-02-12 16:12:36.793 Example[74410:4938944] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSRegularExpression enumerateMatchesInString:options:range:usingBlock:]: nil argument'
```

**Comment by hardikamal** [comment]
@mikeRozen same issue...any solution found??

**Comment by yoonsw15** [comment]
Same here! I'd love to find the solution to this. Does simulators on 9.1 or lower work well?

**Comment by yoonsw15** [comment]
@hardikamal @mikeRozen  I found the reason. Change the baseURL in appdelegate to be https from http. it should work.

**Comment by Guicai-Li** [comment]
@yoonsw15  I change the url, but it doesn't work.

**Comment by andiradulescu** [comment]
@yoonsw15 changing the url to https://api.seatgeek.com/2/ from http://api.seatgeek.com/2/ fixes the issue. thanks!

**Comment by engmsaleh** [comment]
Didn't solve the problem on simulator iOS 10
Also, the API seems to not be working it always timeout.

**Comment by engmsaleh** [comment]
Also, it will not work as the API used in the example have the following change

> Breaking Changes Effective August 1, 2016
> Please Note: Beginning on August 1, 2016 all requests to the SeatGeek API will be required to pass a valid API Key. Our API will remain completely free and open; we are simply asking that API users identify themselves so that we can better ensure the security and reliability of our platform.
> 
> Update: The changes were enabled on December 12, 2016
> 
> You can request an API key here. Note: you will need to create a SeatGeek account to proceed
> 
> Please see the documentation below for more details

**Comment by navamegh** [comment]
I change the url, but it doesn't work.

**Comment by navamegh** [comment]
when i am changing http to https then i got ssl error 
![screen shot 2017-01-02 at 4 46 18 pm](https://cloud.githubusercontent.com/assets/23394290/21589015/1566319a-d113-11e6-8928-180cc66cc038.png)
