### ISSUE TITLE
"UIView"declares the selector 'makeConstraints:' 

### ISSUE THREAD

**Issue by Ruchi-Agrawal-IN** [erichoracek/MSCollectionViewCalendarLayout#69]
Though i have Installed the Pods of 'MSCollectionViewCalendarLayout' still where ever makeConstraints methods is used in all classes errors are stoping to build the code.
I have checked in your example code also but could not find any difference where I can get help.

![masconstraintmaker_issue](https://cloud.githubusercontent.com/assets/13321872/13862727/3e5e363e-ec52-11e5-9da7-25db6f54d929.png)
please find attached file Screen shot also. 

please help me or give any suggestion if have any clues.

**Comment by pavolkmet** [comment]
In **Masonry.h** file after `#import <Foundation/Foundation.h>` you need to add following line `#define MAS_SHORTHAND`
