### ISSUE TITLE
[NSRegularExpression enumerateMatchesInString:options:range:usingBlock:]: nil argument'

### ISSUE THREAD

**Issue by Hitarth2000** [erichoracek/MSCollectionViewCalendarLayout#73]
i have try to run that in xCode7.3 with simulator iPhone 6 (os 9.3)..   Project successfully build but it crash on starting and not opening .

i go below error in log.
**\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '**\* -[NSRegularExpression enumerateMatchesInString:options:range:usingBlock:]: nil argument'
Please help me to resolved this. . is there any setting on this ?

**Comment by Double-Dude** [comment]
Same here

**Comment by tarun567** [comment]
In AppDelegate file change URL "https://api.seatgeek.com/2/"

**Comment by jonchoi** [comment]
Thank you @tarun567
