### ISSUE TITLE
Build this out?

### ISSUE THREAD

**Issue by grosch** [erichoracek/MSCollectionViewCalendarLayout#76]
Any plans to build this out to include month/week views as well?

**Comment by valeIT** [comment]
It's not too hard to do manually, just includo a JTCalendar at the top and this at the bottom and sync the state between them

**Comment by grosch** [comment]
Yes but then I'm playing with two separate calendar components.  I was really hoping to have a single calendar item that had the same look and feel, same general API, etc...
