### ISSUE TITLE
can't get event from api in example app?

### ISSUE THREAD

**Issue by sonysum** [erichoracek/MSCollectionViewCalendarLayout#77]

**Comment by jonchoi** [comment]
![image](https://cloud.githubusercontent.com/assets/9872658/17845727/e7296da2-67f8-11e6-8c4f-fd040c69e18b.png)

**Comment by BadChoice** [comment]
Checkout my fork https://github.com/BadChoice/RVCalendarWeekView
It is updated and with some new features 👯

**Comment by jonchoi** [comment]
@BadChoice with cocoapods 1.0.1, i can't get `pod install` to run. issue with easy date

**Comment by BadChoice** [comment]
@jon-choi  Can you try with 1.1.0.beta.1
This is the version I’m using and it works with no issue

**Comment by DeirdreFu** [comment]
I met the same problem with you, could you tell me you is how to solve?

**Comment by jonchoi** [comment]
![image](https://cloud.githubusercontent.com/assets/9872658/19694788/80e61ef8-9a95-11e6-8600-12174047fbf2.png)

thinking back, I think simply making it a https request solved that issue for me. if that doesn't work, happy to go through my commits to see if there's anything else i missed

**Comment by DeirdreFu** [comment]
@jon-choi Hi, I put the API is modified to HTTPS way can or not.Both HTTP and HTTPS separate apis on the web page cannot be opened.Be sure to use the API to?Later will change?
