### ISSUE TITLE
cocoapods error - not used in any concrete target

### ISSUE THREAD

**Issue by johnheb** [erichoracek/MSCollectionViewCalendarLayout#78]
When trying:  $ pod install    I get the following message:

Johns-iMac:Example iMac$ pod install
Re-creating CocoaPods due to major version update.
Analyzing dependencies
[!] The dependency `MSCollectionViewCalendarLayout (from`../`)` is not used in any concrete target.
The dependency `RestKit` is not used in any concrete target.
The dependency `UIColor-HexString` is not used in any concrete target.
The dependency `Masonry` is not used in any concrete target.
The dependency `MSCollectionViewCalendarLayout` is not used in any concrete target.

[!] xcodeproj was renamed to `project`. Please use that from now on.

Evidently I am doing something wrong with cocoapods. I have added MSCollectionViewCalendarLayout to the Podfile in the Example folder.

If someone could set me straight that would be awesome.

John

**Comment by BadChoice** [comment]
Checkout my fork https://github.com/BadChoice/RVCalendarWeekView
It is updated and with some new features

**Comment by johnheb** [comment]
Jordi,Wow, how did know this was what we were looking for?How is it installed?  Getting errors trying to install the cocoapods: (ver 1.0.1)-iMac:RVCalendarWeekView-master iMac$ pod installAnalyzing dependencies[!] The dependency `Collection` is not used in any concrete target.The dependency `EasyDate` is not used in any concrete target.The dependency `UIColor-HexString` is not used in any concrete target.

The dependency `Masonry` is not used in any concrete target.Barcelona...the best!Thanks againJohn

-------- Original Message --------
Subject: Re: [erichoracek/MSCollectionViewCalendarLayout] cocoapods
error - not used in any concrete target (#78)

**Comment by BadChoice** [comment]
Just updated the repo fixing this pod issue, 
Just post there any issues you find there so we can make it as good as we can

**Comment by Abhinav93** [comment]
RVCalendarWeekView-master/RVCalendarWeekView/Lib/MSWeekViewDragable.m:56:66: No visible @interface for 'NSDate' declares the selector 'withMinute:' getting this on building the project after installing cocoapods

**Comment by BadChoice** [comment]
@Abhinav93 can you check if you have EasyDate pod installed and imported in MSWeekViewDragable.m file?

**Comment by Abhinav93** [comment]
Easy date pod is installed and is imported in the MSWeelViewDragable.m file

**Comment by BadChoice** [comment]
Try to remove the derived data (it happened to me once)

```
rm -rf ~/Library/Developer/Xcode/DerivedData/
```

And build again
