### ISSUE TITLE
Example doesn't work

### ISSUE THREAD

**Issue by jonchoi** [erichoracek/MSCollectionViewCalendarLayout#79]
Would you kindly update the example so that we can check out your project? (which seems awesome!)

![image](https://cloud.githubusercontent.com/assets/9872658/18295670/2d96d944-7458-11e6-999a-f7bc9d9bc445.png)

**Comment by jonchoi** [comment]
Think this is where the issue is happening:
![image](https://cloud.githubusercontent.com/assets/9872658/18357828/46eca00e-75a7-11e6-8747-74898c3bddbe.png)

Related stackoverflow article that i found:
http://stackoverflow.com/questions/10961779/nsregularexpression-enumeratematchesinstringoptionsrangeusingblock-giving-a

any help would be appreciated :)

**Comment by jonchoi** [comment]
using "https" for the seatgeek api call solved the issue. closing out, thanks!

https://github.com/erichoracek/MSCollectionViewCalendarLayout/issues/73

**Comment by DeirdreFu** [comment]
@jon-choi I met the same problem with you, could you tell me how do you solve?

**Comment by BadChoice** [comment]
Check my fork, I fixed it and added some new functionalities 

https://github.com/BadChoice/RVCalendarWeekView

**Comment by DeirdreFu** [comment]
@BadChoice Error can not run, the pods.   When I choose a different date after entering show how to set up to date that I have selected?

**Comment by BadChoice** [comment]
@deidreFu I don't really understand, can you try to explain a bit better or post the error screen?

**Comment by DeirdreFu** [comment]
@BadChoice I just want to ask you to jump to a specified number of effect?Somewhat the same iPhone calendar effect.thank you!
![Uploading 21873B5B-E623-4834-A371-EF6EEDB65828.png…]()
![Uploading timeline.png…]()

**Comment by DeirdreFu** [comment]
![Uploading timeline.png…]()
![Uploading timeline2.png…]()
I just want to ask you to jump to a specified number of effect?Somewhat the same iPhone calendar effect.Thank you very much!

**Comment by DeirdreFu** [comment]
I just want to ask you to jump to a specified number of effect?Somewhat the same iPhone calendar effect.Thank you very much!
<img width="740" alt="timeline2" src="https://cloud.githubusercontent.com/assets/18502296/19468976/e5c35e48-954b-11e6-9efb-eaa061cad26b.png">
<img width="1234" alt="timeline" src="https://cloud.githubusercontent.com/assets/18502296/19469035/2df72faa-954c-11e6-9226-6100385c7036.png">

**Comment by BadChoice** [comment]
There is a function `scrollTo...` on `weekView.flowLayout` class that can work for you

**Comment by jonchoi** [comment]
@DeirdreFu I literally just changed the http request for seatgeek to https. it's been a while since i worked on that project again so i don't remember exactly, but let me know if that doesn't work

**Comment by jonchoi** [comment]
![image](https://cloud.githubusercontent.com/assets/9872658/19694725/59bad9fe-9a95-11e6-92f6-eb5cf77af139.png)
