### ISSUE TITLE
Custom view event

### ISSUE THREAD

**Issue by Bruno-Piccinin-RealComm** [erichoracek/MSCollectionViewCalendarLayout#83]
Is it possible to set custom view on MSEventCell?

I would like to add background image, buttons and multiple labels on MSEventCell.

**Comment by BadChoice** [comment]
Yes, absolutely,
you just need to inhert `MSEventCell` and then inhert `weekView`as well,
in your custom `weekView` just add the following

```
-(void)setupSupplementaryViewClasses{
    [super setupSupplementaryViewClasses];
    self.eventCellClass = YourNewCellClass.class;
}
```

**Comment by BadChoice** [comment]
Just forgot to say, that you should use https://github.com/BadChoice/RVCalendarWeekView that is the current version, sinde mscollectionviewcalendarlayout seems deperecated
